provider "aws"
 {
region= "ap-south-1"
access_key= ""
secret_key= ""
}


resource "aws_instance" "k8s-master" 
{
  ami           = ami-0a7cf821b91bcccbc
  instance_type = "t2.medium"

  tags = {
    Name = "M3"
  }
}

resource "aws_instance" "k8s-slave1" 
{
  ami           = ami-0a7cf821b91bcccbc
  instance_type = "t3.micro"

  tags = {
    Name = "M2"
  }
}

resource "aws_instance" "k8s-slave2" 
{
  ami           = ami-0a7cf821b91bcccbc
  instance_type = "t3.micro"

  tags = {
    Name = "M4"
  }
}