- name: install jenkins and java on local machine
  become: true
  hosts: localhost
  tasks:
  - name: running script
    script: script1.sh
- name: install kubernetes and java on M3
  become: true
  hosts: master
  tasks:
  - name: running script
    script: script2.sh
- name: install kubernetes in M2&4
  become: true
  hosts: slaves
  tasks:
  - name: running script
    script: script3.sh